### ISSUE TITLE
Añadir funcionalidad o eliminar botones de las pestañas estrategias, tipos y factores de riesgos

### ISSUE THREAD

**Issue by MauricioALP** [IngenieriaDeSistemasUTB/altem-utb#12]
Los botones de corazón y basurero no tienen ninguna funcionalidad.

**Comment by LeoM98** [comment]
Los botones que no poseen ninguna funcionalidad serán eliminados completamente de las pestañas mencionadas en el issue. Concretamente esos botones que no poseen ninguna funcionalidad tienen forma de corazón y de una papelera.

![image](https://user-images.githubusercontent.com/54753222/80539915-f6022e00-896d-11ea-8780-82f860f2abaa.png)
