### ISSUE TITLE
Permitir acceso a asesora

### ISSUE THREAD

**Issue by krivera7** [IngenieriaDeSistemasUTB/altem-utb#20]
Buenos días. 
La asesora psicosocial Grace Tirado Tursios es nueva en nuestro equipo de Bienestar, por lo tanto solicito que le permitan el acceso a ALTEM. Su código es T00063208
Gracias

**Comment by MauricioALP** [comment]
Es posible realizar esta función a nivel de usuario desde la pestaña **Control de acceso > Usuarios**

**Comment by krivera7** [comment]
No he podido, cuando le doy guardar no hace nada y por ende no se guarda.

**Comment by jairoserrano** [comment]
Al guardarlo da un error:
Trying to get property of non-object
/var/www/altem/app/Auth/SavioAuth.php#40
ErrorException

**Comment by MauricioALP** [comment]
La creación de usuarios será manejada de manera diferente. Será necesario realizar peticiones por medio de correos electrónicos o la creación de un nuevo issue solicitando que se agregue a un usuario especificando su código y el rol que tomará.

**Comment by jairoserrano** [comment]
Al momento de registrar el usuario en la DB, se tiene que hacer en miniscula...
